# Generated by Django 5.2.4 on 2026-08-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_premium_tests_and_party_emotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentquestion',
            name='selected_choice',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
